name: Deploy NuGet to GitHub Packages 

on:
  push:
    branches: [ master ]
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build project in Release configuration
      run: |
        dotnet build --configuration Release
    - name: Pack a package
      run: dotnet pack --configuration Release
    - name: Publish NuGet Package to GitHub Packages
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
    # Path of NuPkg
        nupkg-path: TeltonikaRMSAPI\bin\Release\TeltonikaRMSAPI*.nupkg
    # package repository owner
        repo-owner: GideonLaar
    # user account
        gh-user: GideonLaar
    # access token
        token: ${{ secrets.GITHUB_TOKEN }}
    # skip publishing duplicated package(s)
        skip-duplicate: true
