name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build project
      run: |
        dotnet build --configuration Release
    - name: Pack a package
      run: dotnet pack --configuration Release
    - name: Publish Nuget package
      uses: myci-actions/publish-nuget@2
      with:
    # nuget package filename, wildcards allowed
        filename: TeltonikaRMSAPI/bin/Release/*
    # API key to access the repository
        api-key: ${{ secrets.GITHUB_TOKEN }}
    # Nuget repository URL
        repo-url: https://nuget.pkg.github.com/GideonLaar/index.json
